{% set version = "0.6.0" %}

package:
  name: nose-parameterized
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nose-parameterized/nose-parameterized-{{ version }}.tar.gz
  sha256: d35e677aba2f15135b6b7ea7feb88f792b899492ba5365ec0e269015df5214ce

build:
  noarch: {{ noarch_python }}
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nose_parameterized

about:
  home: https://github.com/wolever/nose-parameterized
  license: BSD 2-Clause
  summary: 'Parameterized testing with any Python test framework.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
