travis:
  secure:
    BINSTAR_TOKEN: aAtBf1lgKS8KMQlUqWBCtpmJZU/XUiEWxD2oB2PVnNFGzbwlfa64PnmqclXEDx9PZ7IfcZ7of4t7Aeq/Mvj5YXn4J+CqzmVAbq4/BZrNfZgnABkgKbOPW/RuJZ4+TFh4s0p/F0HuqthmD599rz/StFa55aaNzgrdnP3vFbfN1REiKBCu02paRkGE2/ZF6Gw/+b800/2zbtWgXeDB8HKaDYYKI8FHmiijuP/i4xlir69bwqQsZvqhTrz7FSuEASWbREUntUdDxBR+IuypcDs4fEijLd8Y9OZ/o/7OrE0qsmuSEhFLY1lQlCWLxFpqFbnVmHMPWTCWVkIVt8kIPxlIEsc29bD2aeJ29o3vmjeaMJLKYRLMth5ZVv+4CZp7j2jdXz2nFCOyjc673sKdTqPEihlQYP6+J+ZMyNSVnz8DLCHQk0bb+7fAU/EzDKMXKWcnUQYuZtXU5XYM0BbPEpeXlB1RzTeOI1HE6Q02MmFleCnf6sCxyKI4+EjOqYbwbe8xn8vLjMJcS5x3lV1eXICtizF1AgXV8eB4VyKoJHRGHpERz3lJD/j69QGVzWNCUCHOUbCs9jzWFd4wOvTtYOzrk+uOugCEV4agktRc20uCEhtlsIQpFn6VnbaiXpTfKdchDPT6/JLaogVe77+s4IbYo3wQvO21Tjy7ZSIxPukfF7w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
