travis:
  secure:
    BINSTAR_TOKEN: t3k7pNNdJj+Mgp9Vuffbcq+iRlUaoILCJOMIMeJ8KRH5iX3LPEp8pm9EaJBoUP+uNm7PD4EnfUWB9ckvt9RNkr+SykDNs56Qdyh9dohV1ZXiwJXCrheBPpH6sA9rlCnqbeO+tCeYiiJtAslSqtg4mXD2SVt/X0N8z+hlrBKOtBnBlXVz34rs3xOaD0Xzjhhk9kEELfCIvvqtZJdFuoBQs936u7OQA8ensUDR8/uiTrtN1nLYtaE8vm3eOCfBAY0iTScuenUwEjGHnG4bsu0MqVInz5CcSYHDaQs2HgWCLaFXPw2banr8LB60sP5BW2pRzeV5R7CcBRK7IX5zFV4Dr/I3x9311/iTZ6azP+i09N+dN1xggDT/DNWVGmvZTkgCYpZuqtBkaWeNENfhtdDQN2Q1CwdqzXRGYMqDpj6oH8xIOI0cJkzi/rvf+KpqtjiANSwK5MNuRFwdoV3TgbZOpGRne4PEZcM2Gs61TdJbxibjDUDqP39bc3ZfQjqNba4Y34l26ipff5nkRTEg3ACBsmVq50Z+NJ+TeicduzhW3Vg8r8fr9yk8Dfxp+TpV/CYX+gndTLfxvbIEXvzBV5d551ohIr7roiAJ1W+/XREnXLa4xCiu8BAp1fSabbjSjaZJtRAAch/lBjOtCpYRxZzgrloyaIP/XMbUCnO0alu1/K8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
