travis:
  secure:
    BINSTAR_TOKEN: PW7IatAuSqjQU6CqhtPJI9wfmp7ouvgvIFOZKN+83mQIs7K6ojxrhjRNb8TpmL6dz8/V3h2ogkBsTzgG2AM28R17Vu2f3xedVijUpoTZyx+pqX+Bvli1PgOahmPU3WNpHubhGQU5lkw8Tc+pSnWKt76HaCGllv7JXlbA+gEQR2foOiNen5wPQ94HT0/K8J+16o6KHUE9K0V2juyzc4cJqYGBVoifVYav9C77csVtUZJLACdD2anw1lFmAxYL3yghCSsyuF+5hSF2tGB5FeM23jEqTIa1LUpvtMveCaTFRxXLPmB88gt0Io16EvfMsg7Cb4+z7O3h75DhPD2g5jm7BMcO2VoGHcp1c+ztFdBboWQZ4B0ILHlDzgpImShzLuPZd6Grt37OT2UHszYqKlntKf9LPCcD2DhnMm9OQ6X/yB/p/UKsos+VsoMrvKNq2YzFIZQk+QHedcVMDrahEc4JdMvFucH+6GTHEdkuOSh+XoYAehKhyaN3ijEGjbxIoFPKbBQrHCzew3cYe5u+d1KTJszZmhs96Ap7jcVDR6G6p5oA/8liMD1tKFsJGao759kxgwospyouQQW9bOHyVVImOotWuiZ2rsAj3Ux+53+jbMgp5aZi4Fhu23Sgwze/3+/Yvz0N8KUXRbdo1rWo9Gv72WZCwg/DaH11vNOrPgx2Ll4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
